// Code generated by go run gob_gen.go; DO NOT EDIT.

package libchrome

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

// begin of bindings_generator.go
func init() {
	MojomPicklesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(MojomPicklesInfo) })
}

func (r MojomPicklesInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.OutDir); err != nil {
		return err
	}
	return err
}

func (r *MojomPicklesInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.OutDir = nil
	} else {
		r.OutDir = val2.(android.Path)
	}

	return err
}

var MojomPicklesInfoGobRegId int16

func (r MojomPicklesInfo) GetTypeId() int16 {
	return MojomPicklesInfoGobRegId
}

// end of bindings_generator.go
